### ISSUE TITLE
Serial outputs junk

### ISSUE THREAD

**Issue by dizcza** [MappyDot/Testing#1]
Greetings,
I encounter several problems while running test code for mappy dot vl53l0x on arduino uno board.
Firstly, I needed to change `i2c_t3.h` to `Wire.h` as in https://github.com/SensorDots/Testing/commit/0ce07dc2350ab89bbe89d9bb5451af3b4c389ffb.
Secondly, lowering down serial data transmission bit rate from 115200 to 9600 made the hello menu available. However, after the menu the junk is printed:

```
Read: 43
n - device_name_write
s - simple_read
r - read
N - no_restart_read
f - test_non_filtered_distance
B - too_many_bytes
e - error_code
a - distance_accuracy
v - firmware_version
d - device_name
S - settings_read
h - print_menu
1 - set_led_mode_threshold
2 - set_led_mode_on
3 - set_led_mode_off
4 - set_led_mode_pwm
5 - set_led_mode_measurement
6 - set_gpio_mode_threshold
7 - set_gpio_mode_on
8 - set_gpio_mode_off
9 - set_gpio_mode_pwm
0 - set_gpio_mode_measurement
! - set_led_threshold_300
@ - set_led_threshold_100
# - set_gpio_threshold_300
$ - set_gpio_threshold_100
R - read_factory_defaults
W - write_as_startup_settings
F - enter_factory
C - set_continuous
q - set_single
p - perform_single_range
D - measurement_mode_default
H - measurement_mode_high_speed
L - measurement_mode_long_range
A - measurement_mode_high_accurate
c - measurement_mode_custom
I - intersensor_crosstalk_enable
i - intersensor_crosstalk_disable
V - reset_vl53l0x
g - shutdown_vl53l0x
G - startup_vl53l0x
M - averaging_samples_4
X - averaging_samples_10
O - filtering_enable
o - filtering_disable
Y - averaging_enable
y - averaging_disable
- - change_address
? - calibration_routine
k - custom_settings_write_default_profile
K - custom_settings_write_accurate_profile
. - addr_in_test
t - interrupt_read
{ - signal_rate_return
} - ambient_rate_return
Curr⸮w;=s is: 8  aarrs: 4⸮w;=8a⸮⸮⸮
⸮⸮⸮⸮⸮3⸮w;=ar⸮w;=aa⸮⸮⸮⸮⸮⸮
⸮w;=⸮⸮r⸮⸮⸮⸮⸮⸮w;=⸮⸮⸮
⸮r⸮w;=⸮⸮⸮
⸮w;=⸮⸮⸮⸮⸮%⸮w;=⸮rr⸮⸮⸮⸮$⸮w;=⸮
r⸮w;=⸮⸮⸮
⸮w;=⸮w;=⸮⸮⸮⸮⸮⸮w;=r⸮w;=⸮⸮⸮
⸮⸮⸮⸮5⸮w;=⸮r⸮w;=⸮⸮⸮⸮⸮⸮⸮⸮⸮
⸮w;=⸮r⸮⸮⸮-⸮w;=⸮⸮⸮⸮
⸮
⸮w;=
```

The sensor can read the distance in a single shot like the doc states:

`uint16_t distance = Wire.read() << 8; distance |= Wire.read();`

I'd like to see the full functionality available in MappyDot vl53l0x. What is the continous read mode, etc. I hope these tests make it clear. But I need to be able to run them first.

**Comment by bleckers** [comment]
Hey Danylo, apologies I must have missed this issue earlier. If you need anything quickly, please don't hesitate to contact support@sensordots.org

These files are more just examples on how to implement reading the registers as described in the register docs (this gives you more info on what each one is) - https://sensordots.org/mappydotreg
It was originally developed for me to test each function.

Most likely, you would just pick and choose the functions you desire and copy them out.

The issue with the menu and speed is likely to do with the Arduino board you are using. Some Arduino boards cannot operate their serial connections as fast as others and sometimes their buffers aren't large enough (causing the corruption you see). It honestly depends on the type of board as to whether the full file and menu will work or not (as you can see, it was originally used on a Teensy board).
